services:
  apply-executor:
    platform: linux/amd64 # This is needed if running on a Mac M chip laptops
    image: tobikodata/tcloud:latest
    command: executor apply
    restart: unless-stopped
    environment:
      # Tobiko Cloud connection
      TCLOUD_URL: https://cloud.tobikodata.com/sqlmesh/${ORGANIZATION}/${PROJECT}
      TCLOUD_CLIENT_ID: ${TCLOUD_CLIENT_ID}
      TCLOUD_CLIENT_SECRET: ${TCLOUD_CLIENT_SECRET}

      # SQLMesh configuration
      SQLMESH__DEFAULT_GATEWAY: ${DEFAULT_GATEWAY:-TCLOUD_GATEWAY}

      # Example database configuration for BigQuery (adjust for your database)
      # All database parameters below should be customized for your specific setup
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__TYPE: ${DB_TYPE:-bigquery}
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__METHOD: ${DB_METHOD}
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__CONCURRENT_TASKS: ${DB_CONCURRENT_TASKS}
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__REGISTER_COMMENTS: ${DB_REGISTER_COMMENTS}
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__KEYFILE: /app/service-account.json # TODO: update this for your specific file name
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__PROJECT: ${DB_PROJECT}
    volumes:
      # Optional volume for persistent storage if needed
      - apply-executor-data:/app/data
      - ./service-account.json:/app/service-account.json:ro
    deploy:
      resources:
        limits:
          memory: ${APPLY_MEMORY_LIMIT:-4g}
          cpus: ${APPLY_CPU_LIMIT:-2}
        reservations:
          memory: ${APPLY_MEMORY_REQUEST:-2g}
          cpus: ${APPLY_CPU_REQUEST:-1}

  run-executor:
    platform: linux/amd64 # This is needed if running on a Mac M chip laptops
    image: tobikodata/tcloud:latest
    command: executor run
    restart: unless-stopped
    environment:
      # Tobiko Cloud connection
      TCLOUD_URL: https://cloud.tobikodata.com/sqlmesh/${ORGANIZATION}/${PROJECT}
      TCLOUD_CLIENT_ID: ${TCLOUD_CLIENT_ID}
      TCLOUD_CLIENT_SECRET: ${TCLOUD_CLIENT_SECRET}

      # SQLMesh configuration
      SQLMESH__DEFAULT_GATEWAY: ${DEFAULT_GATEWAY:-TCLOUD_GATEWAY}

      # Example database configuration for BigQuery (adjust for your database)
      # All database parameters below should be customized for your specific setup
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__TYPE: ${DB_TYPE:-bigquery}
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__METHOD: ${DB_METHOD}
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__CONCURRENT_TASKS: ${DB_CONCURRENT_TASKS}
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__REGISTER_COMMENTS: ${DB_REGISTER_COMMENTS}
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__KEYFILE: /app/service-account.json # TODO: update this for your specific file name
      SQLMESH__GATEWAYS__TCLOUD_GATEWAY__CONNECTION__PROJECT: ${DB_PROJECT}
    volumes:
      # Optional volume for persistent storage if needed
      - run-executor-data:/app/data
      - ./service-account.json:/app/service-account.json:ro
    deploy:
      resources:
        limits:
          memory: ${RUN_MEMORY_LIMIT:-4g}
          cpus: ${RUN_CPU_LIMIT:-2}
        reservations:
          memory: ${RUN_MEMORY_REQUEST:-2g}
          cpus: ${RUN_CPU_REQUEST:-1}

volumes:
  apply-executor-data: {}
  run-executor-data: {}
